"""A simple interface for dealing with cards."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_card.ipynb.

# %% auto 0
__all__ = ['spades', 'hearts', 'diamonds', 'clubs', 'suits', 'ranks', 'Card']

# %% ../nbs/00_card.ipynb 2
from fastcore.utils import *

# %% ../nbs/00_card.ipynb 5
spades = '♠'
hearts = '♥'
diamonds = '♦'
clubs = '♣'
suits = [spades, hearts, diamonds, clubs]
ranks = ['A', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'] 

# %% ../nbs/00_card.ipynb 7
class Card:
    "A playing card. Created by passing in a `rank` from `ranks` and a `suit` from `suits`."
    def __init__(self, rank, suit): self.rank,self.suit = rank,suit
    def __str__(self): return f"{self.rank}{self.suit}"
    __repr__ = __str__
    

# %% ../nbs/00_card.ipynb 12
@patch
def __eq__(self:Card, card:Card): return (self.rank,self.suit)==(card.rank,card.suit) 
