"""A collection of cards"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_deck.ipynb.

# %% auto 0
__all__ = ['Deck']

# %% ../nbs/01_deck.ipynb 2
from .card import *

# %% ../nbs/01_deck.ipynb 4
class Deck:
    def __init__(self): self.cards = [Card(rank, suit) for rank in ranks for suit in suits]
    def __len__(self): return len(self.cards)
    def __contains__(self, card:Card): return card in self.cards
    def __str__(self): return '; '.join(map(str, self.cards))
    __repr__ = __str__
